version: '3'
services:
  app:
    container_name: lavida
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/lavida/
    depends_on:
      - mysqldb          
    networks:
      - lavida-network


  mysqldb:
    image: mysql:5.7
    container_name: full_db_mysql
    ports: 
      - 3307:3307
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - lavida-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - mysqldb
    environment:
      - PMA_HOST=mysqldb # Note the "mysqldb". Must be the name of the what you used as the mysql service.
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - lavida-network


volumes:
  api:
  database_mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  lavida-network:
    driver: bridge
